travis:
  secure:
    BINSTAR_TOKEN: hHzmz9xQB7reILevtO6/IAPchRqDgfGHgXeoArERR+taGj65ocOE1OI+a4Uf8Cf0jp1gVrxEWllLPgSRTNJB2kTVoaSzwm4IZkEKxtuVWFNiwvQUqOFFfzy6hLCm0RYHj0I9YejjZQChLxsM937C/DU7KjaiRl2eAydhigsIW1KSH++7U/yOAA0uCx/lsTenOCuacVglBd0iRdDyA4yEfFrwe21FgpCOlJ8zRPbqBfx7ScPy+G8/3bwklgfoA2jbmueTkoflEb5EJJL9pboBXVmYsgJwDrR0o4Oq/HwXEtbDBGpdYpc2I8muaCab2Jon/nr9lloZM4RmTtDwryxttiOOMrzVmbPKKmVYfUCAxm3XZ5/OZD6JEQqIVGx0zBIdIAeCQtV6yi6ZFievXobbobCifJ5dFE7WsK/m/Af0OG7kYVXdI1nNGH3+rarPGyVTcE7QtmfGWdXcC0wNsiYSCwh3YOfPtwE6cLheACZDxu5MXIQVsgHUhNIRFqjVc01Jp6W2mHEEKnBbrA4Z7uVwDhq0d2pGeDYBvVsrYR2xXt4WjqQ1cJZ1HNbpLloai38ic8m2zwQixVqfrWB5QOWTgkWm31CUnBj4JWbO9yEdx6RGhqBx7BGKYfeCqvJOkC2d5WZjw0FYXY5aUlkf/Us+I7On7gHUr+XQnehYeizmYy8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
